apiVersion: v1
appVersion: "1.0"
description: Support for DB2 command line interface (CLI)
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - db2
name: db2-client
version: 0.2.1
