apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mssql-tools.fullname" . }}
  labels:
    {{- include "mssql-tools.labels" . | nindent 4 }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.mssql.file }}
          # Reference: https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility
          command: ["/opt/mssql-tools/bin/sqlcmd"]
          args:
            - "-d"
            - {{ .Values.mssql.database }}
            - "-e"
            - "-i"
            - /data/{{ .Values.mssql.file }}
            - "-o"
            - "/dev/stdout"
            - "-P"
            - {{ .Values.mssql.password }}
            - "-S"
            - {{ .Values.mssql.host }}
            - "-U"
            - {{ .Values.mssql.username }}
          {{- else }}
          command: ["sleep"]
          args: ["infinity"]
          {{- end }}
          {{- if .Values.mssql.storageClaim }}
          volumeMounts:
            - name: mssql-storage
              mountPath: /data
          {{- end }}
      restartPolicy: Never
      {{- if .Values.mssql.storageClaim }}
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mssql.storageClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
