apiVersion: v1
appVersion: "1.0"
description: MS-SQL tools
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - mssql
name: mssql-tools
version: 1.0.0
