{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "db2-client.fullname" . }}
  labels:
    app: {{ template "db2-client.name" . }}
    chart: {{ template "db2-client.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
