{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "senzing-init-container.fullname" . }}
  labels:
    app: {{ template "senzing-init-container.name" . }}
    chart: {{ template "senzing-init-container.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
