apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "senzing-mock-data-generator.fullname" . }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.senzing.dataSource }}
            - name: "SENZING_DATA_SOURCE"
              value: "{{ .Values.senzing.dataSource }}"
            {{- end }}
            {{- if .Values.senzing.debug }}
            - name: "SENZING_DEBUG"
              value: "{{ .Values.senzing.debug }}"
            {{- end }}
            {{- if .Values.senzing.entityType }}
            - name: "SENZING_ENTITY_TYPE"
              value: "{{ .Values.senzing.entityType }}"
            {{- end }}
            {{- if .Values.senzing.inputUrl }}
            - name: "SENZING_INPUT_URL"
              value: "{{ .Values.senzing.inputUrl }}"
            {{- end }}
            {{- if .Values.senzing.kafkaBootstrapServerHost }}
            - name: "SENZING_KAFKA_BOOTSTRAP_SERVER"
              value: "{{ .Values.senzing.kafkaBootstrapServerHost }}:{{ .Values.senzing.kafkaBootstrapServerPort }}"
            {{- end }}
            {{- if .Values.senzing.kafkaTopic }}
            - name: "SENZING_KAFKA_TOPIC"
              value: "{{ .Values.senzing.kafkaTopic }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqHost }}
            - name: "SENZING_RABBITMQ_HOST"
              value: "{{ .Values.senzing.rabbitmqHost }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqPassword }}
            - name: "SENZING_RABBITMQ_PASSWORD"
              value: "{{ .Values.senzing.rabbitmqPassword }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqQueue }}
            - name: "SENZING_RABBITMQ_QUEUE"
              value: "{{ .Values.senzing.rabbitmqQueue }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqUsername }}
            - name: "SENZING_RABBITMQ_USERNAME"
              value: "{{ .Values.senzing.rabbitmqUsername }}"
            {{- end }}
            {{- if .Values.senzing.randomSeed }}
            - name: "SENZING_RANDOM_SEED"
              value: "{{ .Values.senzing.randomSeed }}"
            {{- end }}
            {{- if .Values.senzing.recordMax }}
            - name: "SENZING_RECORD_MAX"
              value: "{{ .Values.senzing.recordMax }}"
            {{- end }}
            {{- if .Values.senzing.recordMin }}
            - name: "SENZING_RECORD_MIN"
              value: "{{ .Values.senzing.recordMin }}"
            {{- end }}
            {{- if .Values.senzing.recordMonitor }}
            - name: "SENZING_RECORD_MONITOR"
              value: "{{ .Values.senzing.recordMonitor }}"
            {{- end }}
            {{- if .Values.senzing.recordsPerSecond }}
            - name: "SENZING_RECORDS_PER_SECOND"
              value: "{{ .Values.senzing.recordsPerSecond }}"
            {{- end }}
            {{- if .Values.senzing.subcommand }}
            - name: "SENZING_SUBCOMMAND"
              value: "{{ .Values.senzing.subcommand }}"
            {{- end }}
      restartPolicy: Never
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "senzing-mock-data-generator.fullname" . }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
