{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "senzing-mock-data-generator.fullname" . }}
  labels:
    app: {{ template "senzing-mock-data-generator.name" . }}
    chart: {{ template "senzing-mock-data-generator.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
