# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#deployment-v1-apps

apiVersion: {{ include "senzing-common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "senzing-common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: phppgadmin-component
    {{- if .Values.commonLabels }}
    {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "senzing-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.main.replicaCount }}
  selector:
    matchLabels: {{- include "senzing-common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: phppgadmin-component
  {{- if .Values.main.updateStrategy }}
  strategy: {{- toYaml .Values.main.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.main.podAnnotations }}
      annotations: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "senzing-common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: phppgadmin-component
        {{- if .Values.main.podLabels }}
        {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.main.affinity }}
      affinity: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "senzing-common.affinities.pods" (dict "type" .Values.main.podAffinityPreset "component" "phppgadmin-component" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "senzing-common.affinities.pods" (dict "type" .Values.main.podAntiAffinityPreset "component" "phppgadmin-component" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "senzing-common.affinities.nodes" (dict "type" .Values.main.nodeAffinityPreset.type "key" .Values.main.nodeAffinityPreset.key "values" .Values.main.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      containers:
        - name: phppgadmin
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.main.args }}
          args: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.main.command }}
          command: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.command "context" $) | nindent 12 }}
          {{- end }}
          env:
          - name: PHP_PG_ADMIN_SERVER_HOST
            value: {{ .Values.main.phppgadmin.serverHost | quote }}
          - name: PHP_PG_ADMIN_SERVER_PORT
            value: {{ .Values.main.phppgadmin.serverPort | quote }}
          - name: PHP_PG_ADMIN_SERVER_DESC
            value: {{ .Values.main.phppgadmin.serverDesc | quote }}
          - name: PHP_PG_ADMIN_SERVER_SSL_MODE
            value : {{ .Values.main.phppgadmin.serverSslMode | quote }}
          - name: PHP_PG_ADMIN_SERVER_DEFAULT_DB
            value: {{ .Values.main.phppgadmin.defaultDb | quote }}
          - name: PHP_PG_ADMIN_SERVER_PG_DUMP_PATH
            value: {{ .Values.main.phppgadmin.serverPgDumpPath | quote }}
          - name: PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH
            value: {{ .Values.main.phppgadmin.serverPgDumpAllPath | quote }}
          - name: PHP_PG_ADMIN_DEFAULT_LANG
            value: {{ .Values.main.phppgadmin.defaultLang | quote }}
          - name: PHP_PG_ADMIN_AUTO_COMPLETE
            value: {{ .Values.main.phppgadmin.autoComplete | quote }}
          - name: PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY
            value: {{ .Values.main.phppgadmin.extraLoginSecurity | quote }}
          - name: PHP_PG_ADMIN_OWNED_ONLY
            value: {{ .Values.main.phppgadmin.ownedOnly | quote }}
          - name: PHP_PG_ADMIN_SHOW_COMMENTS
            value: {{ .Values.main.phppgadmin.showComments | quote }}
          - name: PHP_PG_ADMIN_SHOW_ADVANCED
            value: {{ .Values.main.phppgadmin.showAdvanced | quote }}
          - name: PHP_PG_ADMIN_SHOW_SYSTEM
            value: {{ .Values.main.phppgadmin.showSystem | quote }}
          - name: PHP_PG_ADMIN_MIN_PASSWORD_LENGTH
            value: {{ .Values.main.phppgadmin.minPasswordLength | quote }}
          - name: PHP_PG_ADMIN_LEFT_WIDTH
            value: {{ .Values.main.phppgadmin.leftWidth | quote }}
          - name: PHP_PG_ADMIN_THEME
            value: {{ .Values.main.phppgadmin.theme | quote }}
          - name: PHP_PG_ADMIN_SHOW_OIDS
            value: {{ .Values.main.phppgadmin.showOids | quote }}
          - name: PHP_PG_ADMIN_MAX_ROWS
            value: {{ .Values.main.phppgadmin.maxRows | quote }}
          - name: PHP_PG_ADMIN_MAX_CHARS
            value: {{ .Values.main.phppgadmin.maxChars | quote }}
          - name: PHP_PG_ADMIN_USE_XHTML_STRICT
            value: {{ .Values.main.phppgadmin.useXhtmlStrict | quote }}
          - name: PHP_PG_ADMIN_HELP_BASE
            value: {{ .Values.main.phppgadmin.helpBase | quote }}
          - name: PHP_PG_ADMIN_AJAX_REFRESH
            value: {{ .Values.main.phppgadmin.ajaxRefresh | quote }}
            {{- if .Values.main.extraEnvVars }}
            {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.main.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.main.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVarsSecret "context" $) }}
            {{- end }}
          image: {{ template "phppgadmin.image" . }}
          imagePullPolicy: {{ .Values.main.image.pullPolicy }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.main.lifecycleHooks }}
          lifecycle: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.main.livenessProbe.enabled }}
          livenessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" (omit .Values.main.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.main.customLivenessProbe }}
          livenessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.main.containerPorts.http }}
            - name: https
              containerPort: {{ .Values.main.containerPorts.https }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.main.readinessProbe.enabled }}
          readinessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" (omit .Values.main.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.main.customReadinessProbe }}
          readinessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.main.resources }}
          resources: {{- toYaml .Values.main.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.main.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.main.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.main.startupProbe.enabled }}
          startupProbe: {{- include "senzing-common.tplvalues.render" (dict "value" (omit .Values.main.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.main.customStartupProbe }}
          startupProbe: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.main.extraVolumeMounts }}
            {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.main.sidecars }}
        {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.sidecars "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.main.hostAliases }}
      hostAliases: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- include "phppgadmin.imagePullSecrets" . | nindent 6 }}
      initContainers:
        {{- if .Values.volumePermissions.enabled }}
        - command:
            - %%commands%%
          image: {{ include "phppgadmin.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          name: volume-permissions
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          securityContext: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.volumePermissions.containerSecurityContext "context" $) | nindent 12 }}
          volumeMounts:
            - mountPath: bar
              name: foo
        {{- end }}
        {{- if .Values.main.initContainers }}
          {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.main.nodeSelector }}
      nodeSelector: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.main.priorityClassName }}
      priorityClassName: {{ .Values.main.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.main.schedulerName }}
      schedulerName: {{ .Values.main.schedulerName | quote }}
      {{- end }}
      {{- if .Values.main.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.main.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "phppgadmin.serviceAccountName" . }}
      {{- if .Values.main.tolerations }}
      tolerations: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.tolerations "context" .) | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.main.extraVolumes }}
        {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
