# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/

{{- if .Values.main.autoscaling.enabled }}
apiVersion: {{ include "senzing-common.capabilities.horizontalpodautoscaler.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "senzing-common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: phppgadmin-component
    {{- if .Values.commonLabels }}
    {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "senzing-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "senzing-common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "senzing-common.names.fullname" . }}
  minReplicas: {{ .Values.main.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.main.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.main.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.main.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.main.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.main.autoscaling.targetMemory  }}
    {{- end }}
{{- end }}
