apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ibm-db2-driver-installer.fullname" . }}
  labels:
    {{- include "ibm-db2-driver-installer.labels" . | nindent 4 }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.rbacEnabled}}
          securityContext:
            privileged: true
          {{- end }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/IBM
              subPath: senzing-db2-drivers
      restartPolicy: Never
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "ibm-db2-driver-installer.fullname" . }}
      {{- end }}
      {{- if .Values.senzing.persistentVolumeClaim }}
      volumes:
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.persistentVolumeClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
