{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ibm-db2-driver-installer.fullname" . }}
  labels:
    app: {{ template "ibm-db2-driver-installer.name" . }}
    chart: {{ template "ibm-db2-driver-installer.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
