affinity: {}

deployment:
  metadata:
    annotations:
  spec:
    template:
      metadata:
        annotations:

fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: arey/mysql-client
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

mysql:
  database: G2
  file: senzing-g2/resources/schema/g2core-schema-mysql-create.sql
  host: ""
  password: g2
  persistentVolumeClaim: senzing-persistent-volume-claim
  username: g2

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

tolerations: []
