apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "senzing-common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: nemoComponent
    {{- if .Values.commonLabels }}
    {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "senzing-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels: {{- include "senzing-common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: nemoComponent
  template:
    metadata:
      {{- if .Values.main.podAnnotations }}
      annotations: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "senzing-common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: nemoComponent
        {{- if .Values.main.podLabels }}
        {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.main.affinity }}
      affinity: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "senzing-common.affinities.pods" (dict "type" .Values.main.podAffinityPreset "component" "nemoComponent" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "senzing-common.affinities.pods" (dict "type" .Values.main.podAntiAffinityPreset "component" "nemoComponent" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "senzing-common.affinities.nodes" (dict "type" .Values.main.nodeAffinityPreset.type "key" .Values.main.nodeAffinityPreset.key "values" .Values.main.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      containers:
        - name: senzing-nemo
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.main.args }}
          args: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.main.command }}
          command: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.command "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: SENZING_DEBUG
              value: {{ ternary "true" "false" (or .Values.main.image.debug .Values.diagnosticMode.enabled) | quote }}
            {{- if .Values.main.extraEnvVars }}
            {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.main.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.main.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVarsSecret "context" $) }}
            {{- end }}
          image: {{ template "senzing-nemo.image" . }}
          imagePullPolicy: {{ .Values.main.image.pullPolicy }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.main.lifecycleHooks }}
          lifecycle: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.main.livenessProbe.enabled }}
          livenessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" (omit .Values.main.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.main.customLivenessProbe }}
          livenessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: foo
              protocol: bar
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.main.readinessProbe.enabled }}
          readinessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" (omit .Values.main.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.main.customReadinessProbe }}
          readinessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.main.resources }}
          resources: {{- toYaml .Values.main.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.main.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.main.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: bar
              name: foo
              readOnly: true
            {{- if .Values.main.extraVolumeMounts }}
            {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.main.sidecars }}
        {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.sidecars "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.main.hostAliases }}
      hostAliases: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- include "senzing-nemo.imagePullSecrets" . | nindent 6 }}
      initContainers:
        {{- if .Values.volumePermissions.enabled }}
        - command:
            - %%commands%%
          image: {{ include "senzing-nemo.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          name: volume-permissions
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: bar
              name: foo
        {{- end }}
        {{- if .Values.main.initContainers }}
          {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.main.nodeSelector }}
      nodeSelector: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.main.priorityClassName }}
      priorityClassName: {{ .Values.main.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.main.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.main.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "senzing-nemo.serviceAccountName" . }}
      {{- if .Values.main.tolerations }}
      tolerations: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.tolerations "context" .) | nindent 8 }}
      {{- end }}
      volumes:
        - name: foo
          hostPath:
            path: bar
        {{- if .Values.main.extraVolumes }}
        {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
  {{- if .Values.main.updateStrategy }}
  updateStrategy: {{- toYaml .Values.main.updateStrategy | nindent 4 }}
  {{- end }}
