{{- if .Values.rbacEnabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "senzing-common.names.fullname" . }}-endpoint-reader
  labels: {{- include "senzing-common.labels.standard" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
{{- end }}
