affinity: {}

deployment:
  metadata:
    annotations:
  spec:
    template:
      metadata:
        annotations:

fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/entity-search-web-app
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

senzing:
  apiServerUrl: kafka
  persistentVolumeClaim: senzing-persistent-volume-claim
  webServerPort: 8081

service:
  port: 80
  type: ClusterIP

tolerations: []
