apiVersion: v1
appVersion: "1.0"
description: A Helm chart for github.com/coleifer/sqlite-web
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - sqlite
name: coleifer-sqlite-web
sources:
 - https://github.com/coleifer/sqlite-web
version: 1.1.3
