apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgresql-client.fullname" . }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "PGPASSWORD"
              value: "{{ .Values.postgresql.password }}"
          command: ["psql"]
          args:
            - "-U"
            - {{ .Values.postgresql.username }}
            - "-h"
            - {{ .Values.postgresql.host }}
            - "-d"
            - {{ .Values.postgresql.database }}
            - "-f"
            - "/data/{{ .Values.postgresql.file }}"
          {{- if .Values.postgresql.storageClaim }}
          volumeMounts:
            - name: postgresql-storage
              mountPath: /data
          {{- end }}
      restartPolicy: Never
      {{- if .Values.postgresql.storageClaim }}
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.storageClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
