# https://helm.sh/docs/topics/charts/#the-chartyaml-file

apiVersion: v2
appVersion: ""
dependencies:
  - name: senzing-common
    repository: https://hub.senzing.com/charts/
    version: 1.0.2
description: A Senzing environment for ephemeral entity resolution.
engine: gotpl
home: https://github.com/Senzing/charts/tree/main/charts/senzing-resolver
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
  - senzing
maintainers:
  - email: support@senzing.com
    name: Senzing
name: senzing-resolver
sources:
  - https://github.com/Senzing/charts/tree/main/charts/senzing-template
  - https://github.com/Senzing/resolver
type: application
version: 2.0.1
