apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mysql-client.fullname" . }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--user={{ .Values.mysql.username }}"
            - "--password={{ .Values.mysql.password }}"
            - "--host={{ .Values.mysql.host }}"
            - "--database={{ .Values.mysql.database }}"
            - "--execute=source /sql/{{ .Values.mysql.file }}"
          {{ if .Values.mysql.persistentVolumeClaim }}
          volumeMounts:
            - name: mysql-storage
              mountPath: /sql
          {{ end }}
      restartPolicy: Never
      {{ if .Values.mysql.persistentVolumeClaim }}
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.persistentVolumeClaim }}
      {{ end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
