affinity: {}

deployment:
  metadata:
    annotations:
  spec:
    template:
      metadata:
        annotations:

fullnameOverride: ""

db2:
  db2instPassword: db2inst1
  license: accept
  persistentVolumeClaim: db2-database-claim

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/ibm-db2
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

senzing:
  persistentVolumeClaim: senzing-persistent-volume-claim

service:
  port: 50000
  type: ClusterIP

tolerations: []
