# https://helm.sh/docs/topics/charts/#the-chartyaml-file

apiVersion: v2
appVersion: ""
dependencies:
  - name: senzing-common
    repository: https://hub.senzing.com/charts/
    version: 1.0.1
description: MySQL client
engine: gotpl
home: https://github.com/Senzing/charts/tree/master/charts/arey-mysql-client
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
  - mysql
maintainers:
  - email: support@senzing.com
    name: Senzing
name: arey-mysql-client
sources:
  - https://github.com/Senzing/charts/tree/master/charts/arey-mysql-client
  - https://github.com/arey/mysql-client
type: application
version: 2.0.0
