{{- if .Values.rbacEnabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "senzing-base.fullname" . }}-endpoint-reader
  labels:
    app: {{ template "senzing-base.name" . }}
    chart: {{ template "senzing-base.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ template "senzing-base.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "senzing-base.fullname" . }}-endpoint-reader
{{- end }}
