# https://helm.sh/docs/topics/charts/#the-chartyaml-file

apiVersion: v2
appVersion: ""
dependencies:
  - name: senzing-common
    repository: https://hub.senzing.com/charts/
    version: 1.0.1
description: phpPgAdmin is a web-based administration tool for PostgreSQL. It is perfect for PostgreSQL DBAs, newbies, and hosting services.
engine: gotpl
home: https://github.com/phppgadmin/phppgadmin
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
  - phppgadmin
  - postgresql
  - database
  - sql
maintainers:
  - email: support@senzing.com
    name: Senzing
name: phppgadmin
sources:
  - https://github.com/Senzing/charts/tree/master/charts/phppgadmin
type: application
version: 3.2.1
