affinity: {}

deployment:
  metadata:
    annotations:
  spec:
    template:
      metadata:
        annotations:

fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: confluentinc/cp-kafka
  tag: 4.0.1-1

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

service:
  port: 80
  type: ClusterIP

tolerations: []
