# https://helm.sh/docs/topics/charts/#the-chartyaml-file

apiVersion: v2
appVersion: ""
dependencies:
  - name: senzing-common
    repository: https://hub.senzing.com/charts/
    version: 1.0.1
description: A wrapper over yum package installer prepared for Senzing installs
engine: gotpl
home: https://github.com/Senzing/charts/tree/master/charts/senzing-yum
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
 - install
maintainers:
  - email: support@senzing.com
    name: Senzing
name: senzing-yum
sources:
 - https://github.com/Senzing/charts/tree/master/charts/senzing-yum
 - https://github.com/Senzing/docker-yum
type: application
version: 2.1.0
