# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#job-v1-batch

apiVersion: batch/v1
kind: Job
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "senzing-common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: senzing-yum-component
    {{- if .Values.commonLabels }}
    {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "senzing-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  template:
    metadata:
      {{- if .Values.main.podAnnotations }}
      annotations: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "senzing-common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: senzing-yum-component
        {{- if .Values.main.podLabels }}
        {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.main.affinity }}
      affinity: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "senzing-common.affinities.pods" (dict "type" .Values.main.podAffinityPreset "component" "senzing-yum-component" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "senzing-common.affinities.pods" (dict "type" .Values.main.podAntiAffinityPreset "component" "senzing-yum-component" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "senzing-common.affinities.nodes" (dict "type" .Values.main.nodeAffinityPreset.type "key" .Values.main.nodeAffinityPreset.key "values" .Values.main.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      containers:
        - name: senzing-yum
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.main.args }}
          args: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.main.command }}
          command: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.command "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.main.senzing.acceptEula }}
            - name: "SENZING_ACCEPT_EULA"
              value: {{ .Values.main.senzing.acceptEula | quote }}
            {{- end }}
            {{- if .Values.main.mssql.acceptEula }}
            - name: "ACCEPT_EULA"
              value: {{ .Values.main.mssql.acceptEula | quote }}
            {{- end }}
            {{- if .Values.main.extraEnvVars }}
            {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.main.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.main.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraEnvVarsSecret "context" $) }}
            {{- end }}
          image: {{ template "senzing-yum.image" . }}
          imagePullPolicy: {{ .Values.main.image.pullPolicy }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.main.lifecycleHooks }}
          lifecycle: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.main.livenessProbe.enabled }}
          livenessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" (omit .Values.main.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.main.customLivenessProbe }}
          livenessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.main.readinessProbe.enabled }}
          readinessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" (omit .Values.main.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.main.customReadinessProbe }}
          readinessProbe: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.main.resources }}
          resources: {{- toYaml .Values.main.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.main.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.main.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.main.startupProbe.enabled }}
          startupProbe: {{- include "senzing-common.tplvalues.render" (dict "value" (omit .Values.main.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.main.customStartupProbe }}
          startupProbe: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.main.senzing.persistentVolumeClaim }}
            - name: senzing-storage
              mountPath: /opt/senzing/data
              subPath: senzing-data
            - name: senzing-storage
              mountPath: /etc/opt/senzing
              subPath: senzing-etc
            - name: senzing-storage
              mountPath: /opt/senzing/g2
              subPath: senzing-g2
            - name: senzing-storage
              mountPath: /rpms
              subPath: senzing-rpms
            - name: senzing-storage
              mountPath: /var/opt/senzing
              subPath: senzing-var
            {{- if .Values.main.senzing.mountOptIbm }}
            - name: senzing-storage
              mountPath: /opt/IBM
              subPath: senzing-db2-drivers
            {{- end }}
            {{- if .Values.main.senzing.mountOptMicrosoft }}
            - name: senzing-storage
              mountPath: /opt/microsoft
              subPath: opt-microsoft
            {{- end }}
            {{- end }}
            {{- if .Values.main.extraVolumeMounts }}
            {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.main.sidecars }}
        {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.sidecars "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.main.hostAliases }}
      hostAliases: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- include "senzing-yum.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: senzing-mount-maker
          image: busybox:1.28
          {{- if .Values.rbac.enabled}}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.main.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name:  senzing-storage
              mountPath: /opt/senzing
          {{- end }}
        {{- if .Values.main.initContainers }}
          {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.main.nodeSelector }}
      nodeSelector: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.main.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.main.priorityClassName }}
      priorityClassName: {{ .Values.main.priorityClassName | quote }}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.main.schedulerName }}
      schedulerName: {{ .Values.main.schedulerName | quote }}
      {{- end }}
      {{- if .Values.main.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.main.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "senzing-common.names.fullname" . }}
      {{- if .Values.main.tolerations }}
      tolerations: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.tolerations "context" .) | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.main.senzing.optMicrosoftDataClaim }}
        - name: opt-microsoft
          persistentVolumeClaim:
            claimName: {{ .Values.main.senzing.optMicrosoftDataClaim }}
        {{- end }}
        {{- if .Values.main.senzing.senzingDataClaim }}
        - name: senzing-data-storage
          persistentVolumeClaim:
            claimName: {{ .Values.main.senzing.senzingDataClaim }}
        {{- end }}
        {{- if .Values.main.senzing.senzingEtcClaim }}
        - name: senzing-etc-storage
          persistentVolumeClaim:
            claimName: {{ .Values.main.senzing.senzingEtcClaim }}
        {{- end }}
        {{- if .Values.main.senzing.senzingG2Claim }}
        - name: senzing-g2-storage
          persistentVolumeClaim:
            claimName: {{ .Values.main.senzing.senzingG2Claim }}
        {{- end }}
        {{- if .Values.main.senzing.persistentVolumeClaim }}
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.main.senzing.persistentVolumeClaim }}
        {{- end }}
        {{- if .Values.main.senzing.senzingVarClaim }}
        - name: senzing-var-storage
          persistentVolumeClaim:
            claimName: {{ .Values.main.senzing.senzingVarClaim }}
        {{- end }}
        {{- if .Values.main.extraVolumes }}
        {{- include "senzing-common.tplvalues.render" (dict "value" .Values.main.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
