# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/

apiVersion: {{ include "senzing-common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "senzing-common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "senzing-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "senzing-common.labels.matchLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.updateStrategy "context" $ ) | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- include "senzing-common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "senzing-common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "senzing-common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "senzing-common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "senzing-common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "senzing-common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.senzinzg.args }}
          args: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.senzing.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.senzing.command }}
          command: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.senzing.command "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.senzing.mountOptIbm }}
            - name: LD_LIBRARY_PATH
              value: /opt/senzing/g2/lib:/opt/senzing/g2/lib/debian:/opt/IBM/db2/clidriver/lib
            {{- end }}
            {{- if .Values.senzing.mountOptMicrosoft }}
            - name: LD_LIBRARY_PATH
              value: /opt/senzing/g2/lib:/opt/senzing/g2/lib/debian:/opt/microsoft/msodbcsql17/lib64
            - name: ODBCINI
              value: /opt/microsoft/msodbcsql17/etc/odbc.ini
            - name: ODBCSYSINI
              value: /opt/microsoft/msodbcsql17/etc
            {{- end }}
            {{- if .Values.senzing.debug }}
            - name: SENZING_DEBUG
              value: "{{ .Values.senzing.debug }}"
            {{- end }}
            {{- if .Values.senzing.logLevel }}
            - name: SENZING_LOG_LEVEL
              value: "{{ .Values.senzing.logLevel }}"
            {{- end }}
            {{- if .Values.extraEnvVars }}
              {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.extraEnvVarsCM }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
            {{- end }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/senzing/data
              subPath: senzing-data/2.0.0
            - name: senzing-storage
              mountPath: /etc/opt/senzing
              subPath: senzing-etc
            - name: senzing-storage
              mountPath: /opt/senzing/g2
              subPath: senzing-g2
            - name: senzing-storage
              mountPath: /var/opt/senzing
              subPath: senzing-var
            {{- if .Values.senzing.mountOptIbm }}
            - name: senzing-storage
              mountPath: /opt/IBM
              subPath: senzing-db2-drivers
            {{- end }}
            {{- if .Values.senzing.mountOptMicrosoft }}
            - name: senzing-storage
              mountPath: /opt/microsoft
              subPath: opt-microsoft
            {{- end }}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.imagePullSecrets "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeName }}
      nodeName: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.nodeName "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{- include "senzing-common.tplvalues.render" ( dict "value" .Values.schedulerName "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "senzing-stream-loader.fullname" . }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "senzing-common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.senzing.persistentVolumeClaim }}
      volumes:
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.persistentVolumeClaim }}
      {{- end }}
