apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senzing-entity-search-web-app.fullname" . }}
  labels:
    {{- include "senzing-entity-search-web-app.labels" . | nindent 4 }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senzing-entity-search-web-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "senzing-entity-search-web-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- if .Values.senzing.apiServerUrl }}
            - name: SENZING_API_SERVER_URL
              value: "{{ .Values.senzing.apiServerUrl}}"
            {{- end }}
            {{- if .Values.senzing.authServerAdminJwpathRewrite }}
            - name: SENZING_AUTH_SERVER_ADMIN_JWTPATH_REWRITE
              value: "{{ .Values.senzing.authServerAdminJwpathRewrite }}"
            {{- end }}
            {{- if .Values.senzing.authServerAdminSsopathRewrite }}
            - name: SENZING_AUTH_SERVER_ADMIN_SSOPATH_REWRITE
              value: "{{ .Values.senzing.authServerAdminSsopathRewrite }}"
            {{- end }}
            {{- if .Values.senzing.authServerHostname }}
            - name: SENZING_AUTH_SERVER_HOSTNAME
              value: "{{ .Values.senzing.authServerHostname }}"
            {{- end }}
            {{- if .Values.senzing.authServerJwpathRewrite }}
            - name: SENZING_AUTH_SERVER_JWTPATH_REWRITE
              value: "{{ .Values.senzing.authServerJwpathRewrite }}"
            {{- end }}
            {{- if .Values.senzing.authServerPort }}
            - name: SENZING_AUTH_SERVER_PORT
              value: "{{ .Values.senzing.authServerPort }}"
            {{- end }}
            {{- if .Values.senzing.authServerSsopathRewrite }}
            - name: SENZING_AUTH_SERVER_SSOPATH_REWRITE
              value: "{{ .Values.senzing.authServerSsopathRewrite }}"
            {{- end }}
            {{- if .Values.senzing.authServerWriteConfigToFile }}
            - name: SENZING_AUTH_SERVER_WRITE_CONFIG_TO_FILE
              value: "{{ .Values.senzing.authServerWriteConfigToFile }}"
            {{- end }}
            {{- if .Values.senzing.webServerAdminAuthMode }}
            - name: SENZING_WEB_SERVER_ADMIN_AUTH_MODE
              value: "{{ .Values.senzing.webServerAdminAuthMode }}"
            {{- end }}
            {{- if .Values.senzing.webServerAdminAuthPath }}
            - name: SENZING_WEB_SERVER_ADMIN_AUTH_PATH
              value: "{{ .Values.senzing.webServerAdminAuthPath }}"
            {{- end }}
            {{- if .Values.senzing.webServerAdminAuthRedirect }}
            - name: SENZING_WEB_SERVER_ADMIN_AUTH_REDIRECT
              value: "{{ .Values.senzing.webServerAdminAuthRedirect }}"
            {{- end }}
            {{- if .Values.senzing.webServerAdminAuthStatus }}
            - name: SENZING_WEB_SERVER_ADMIN_AUTH_STATUS
              value: "{{ .Values.senzing.webServerAdminAuthStatus }}"
            {{- end }}
            {{- if .Values.senzing.webServerAdminSecret }}
            - name: SENZING_WEB_SERVER_ADMIN_SECRET
              value: "{{ .Values.senzing.webServerAdminSecret }}"
            {{- end }}
            {{- if .Values.senzing.webServerAdminSeed }}
            - name: SENZING_WEB_SERVER_ADMIN_SEED
              value: "{{ .Values.senzing.webServerAdminSeed }}"
            {{- end }}
            {{- if .Values.senzing.webServerApiPath }}
            - name: SENZING_WEB_SERVER_API_PATH
              value: "{{ .Values.senzing.webServerApiPath }}"
            {{- end }}
            {{- if .Values.senzing.webServerAuthPath }}
            - name: SENZING_WEB_SERVER_AUTH_PATH
              value: "{{ .Values.senzing.webServerAuthPath }}"
            {{- end }}
            {{- if .Values.senzing.webServerBasicAuthJson }}
            - name: SENZING_WEB_SERVER_BASIC_AUTH_JSON
              value: "{{ .Values.senzing.webServerBasicAuthJson }}"
            {{- end }}
            {{- if .Values.senzing.webServerCorsAllowedOrigin }}
            - name: SENZING_WEB_SERVER_CORS_ALLOWED_ORIGIN
              value: "{{ .Values.senzing.webServerCorsAllowedOrigin }}"
            {{- end }}
            {{- if .Values.senzing.webServerHosname }}
            - name: SENZING_WEB_SERVER_HOSTNAME
              value: "{{ .Values.senzing.webServerHosname }}"
            {{- end }}
            {{- if .Values.senzing.webServerOperatorAuthMode }}
            - name: SENZING_WEB_SERVER_OPERATOR_AUTH_MODE
              value: "{{ .Values.senzing.webServerOperatorAuthMode }}"
            {{- end }}
            {{- if .Values.senzing.webServerOperatorAuthRedirect }}
            - name: SENZING_WEB_SERVER_OPERATOR_AUTH_REDIRECT
              value: "{{ .Values.senzing.webServerOperatorAuthRedirect }}"
            {{- end }}
            {{- if .Values.senzing.webServerOperatorAuthStatus }}
            - name: SENZING_WEB_SERVER_OPERATOR_AUTH_STATUS
              value: "{{ .Values.senzing.webServerOperatorAuthStatus }}"
            {{- end }}
            {{- if .Values.senzing.webServerPort }}
            - name: SENZING_WEB_SERVER_PORT
              value: "{{ .Values.senzing.webServerPort }}"
            {{- end }}
            {{- if .Values.senzing.webServerProxyLoglevel }}
            - name: SENZING_WEB_SERVER_PROXY_LOGLEVEL
              value: "{{ .Values.senzing.webServerProxyLoglevel }}"
            {{- end }}
            {{- if .Values.senzing.webServerSslCertPath }}
            - name: SENZING_WEB_SERVER_SSL_CERT_PATH
              value: "{{ .Values.senzing.webServerSslCertPath }}"
            {{- end }}
            {{- if .Values.senzing.webServerSslKeyPath }}
            - name: SENZING_WEB_SERVER_SSL_KEY_PATH
              value: "{{ .Values.senzing.webServerSslKeyPath }}"
            {{- end }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/senzing/data
              subPath: senzing-data/2.0.0
            - name: senzing-storage
              mountPath: /etc/opt/senzing
              subPath: senzing-etc
            - name: senzing-storage
              mountPath: /opt/senzing/g2
              subPath: senzing-g2
            - name: senzing-storage
              mountPath: /var/opt/senzing
              subPath: senzing-var
          {{- end }}
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "senzing-entity-search-web-app.fullname" . }}
      {{- end }}
      {{- if .Values.senzing.persistentVolumeClaim }}
      volumes:
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.persistentVolumeClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
