apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "senzing-stream-producer.fullname" . }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.senzing.awsAccessKeyId }}
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.senzing.awsAccessKeyId }}"
            {{- end }}
            {{- if .Values.senzing.awsDefaultRegion }}
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.senzing.awsDefaultRegion }}"
            {{- end }}
            {{- if .Values.senzing.awsSecretAccessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.senzing.awsSecretAccessKey }}"
            {{- end }}
            {{- if .Values.senzing.awsSessionToken }}
            - name: AWS_SESSION_TOKEN
              value: "{{ .Values.senzing.awsSessionToken }}"
            {{- end }}
            {{- if .Values.senzing.debug }}
            - name: SENZING_DEBUG
              value: "{{ .Values.senzing.debug }}"
            {{- end }}
            {{- if .Values.senzing.defaultDataSource }}
            - name: SENZING_DEFAULT_DATA_SOURCE
              value: "{{ .Values.senzing.defaultDataSource }}"
            {{- end }}
            {{- if .Values.senzing.defaultEntityType }}
            - name: SENZING_DEFAULT_ENTITY_TYPE
              value: "{{ .Values.senzing.defaultEntityType }}"
            {{- end }}
            {{- if .Values.senzing.delayInSeconds }}
            - name: SENZING_DELAY_IN_SECONDS
              value: "{{ .Values.senzing.delayInSeconds }}"
            {{- end }}
            {{- if .Values.senzing.inputUrl }}
            - name: SENZING_INPUT_URL
              value: "{{ .Values.senzing.inputUrl }}"
            {{- end }}
            {{- if .Values.senzing.kafkaBootstrapServerHost }}
            - name: SENZING_KAFKA_BOOTSTRAP_SERVER
              value: "{{ .Values.senzing.kafkaBootstrapServerHost }}:{{ .Values.senzing.kafkaBootstrapServerPort }}"
            {{- end }}
            {{- if .Values.senzing.kafkaTopic }}
            - name: SENZING_KAFKA_TOPIC
              value: "{{ .Values.senzing.kafkaTopic }}"
            {{- end }}
            {{- if .Values.senzing.kafkaPollInterval }}
            - name: SENZING_KAFKA_POLL_INTERVAL
              value: "{{ .Values.senzing.kafkaPollInterval }}"
            {{- end }}
            {{- if .Values.senzing.monitoringPeriodInSeconds }}
            - name: SENZING_MONITORING_PERIOD_IN_SECONDS
              value: "{{ .Values.senzing.monitoringPeriodInSeconds }}"
            {{- end }}
            {{- if .Values.senzing.password }}
            - name: SENZING_PASSWORD
              value: "{{ .Values.senzing.password }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqExchange }}
            - name: SENZING_RABBITMQ_EXCHANGE
              value: "{{ .Values.senzing.rabbitmqExchange }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqHost }}
            - name: SENZING_RABBITMQ_HOST
              value: "{{ .Values.senzing.rabbitmqHost }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqPassword }}
            - name: SENZING_RABBITMQ_PASSWORD
              value: "{{ .Values.senzing.rabbitmqPassword }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqPort }}
            - name: SENZING_RABBITMQ_PORT
              value: "{{ .Values.senzing.rabbitmqPort }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqQueue }}
            - name: SENZING_RABBITMQ_QUEUE
              value: "{{ .Values.senzing.rabbitmqQueue }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqRoutingKey }}
            - name: SENZING_RABBITMQ_ROUTING_KEY
              value: "{{ .Values.senzing.rabbitmqRoutingKey }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqUsername }}
            - name: SENZING_RABBITMQ_USERNAME
              value: "{{ .Values.senzing.rabbitmqUsername }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqUseExistingEntities }}
            - name: SENZING_RABBITMQ_USE_EXISTING_ENTITIES
              value: "{{ .Values.senzing.rabbitmqUseExistingEntities }}"
            {{- end }}
            {{- if .Values.senzing.readQueueMaxSize }}
            - name: SENZING_READ_QUEUE_MAXSIZE
              value: "{{ .Values.senzing.readQueueMaxSize }}"
            {{- end }}
            {{- if .Values.senzing.recordMax }}
            - name: SENZING_RECORD_MAX
              value: "{{ .Values.senzing.recordMax }}"
            {{- end }}
            {{- if .Values.senzing.recordMin }}
            - name: SENZING_RECORD_MIN
              value: "{{ .Values.senzing.recordMin }}"
            {{- end }}
            {{- if .Values.senzing.recordMonitor }}
            - name: SENZING_RECORD_MONITOR
              value: "{{ .Values.senzing.recordMonitor }}"
            {{- end }}
            {{- if .Values.senzing.sleepTimeInSeconds }}
            - name: SENZING_SLEEP_TIME_IN_SECONDS
              value: "{{ .Values.senzing.sleepTimeInSeconds }}"
            {{- end }}
            {{- if .Values.senzing.sqsDelaySeconds }}
            - name: SENZING_SQS_DELAY_SECONDS
              value: "{{ .Values.senzing.sqsDelaySeconds }}"
            {{- end }}
            {{- if .Values.senzing.sqsQueueUrl }}
            - name: SENZING_SQS_QUEUE_URL
              value: "{{ .Values.senzing.sqsQueueUrl }}"
            {{- end }}
            {{- if .Values.senzing.subcommand }}
            - name: SENZING_SUBCOMMAND
              value: "{{ .Values.senzing.subcommand }}"
            {{- end }}
            {{- if .Values.senzing.threadsPerUnit }}
            - name: SENZING_THREADS_PER_UNIT
              value: "{{ .Values.senzing.threadsPerUnit }}"
            {{- end }}
      restartPolicy: Never
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "senzing-stream-producer.fullname" . }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
