{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "senzing-stream-producer.fullname" . }}
  labels:
    app: {{ template "senzing-stream-producer.name" . }}
    chart: {{ template "senzing-stream-producer.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
