# https://helm.sh/docs/topics/charts/#the-chartyaml-file

apiVersion: v2
appVersion: ""
dependencies:
  - name: senzing-common
    repository: https://hub.senzing.com/charts/
    version: 1.0.2
description: Processes Senzing redo records
engine: gotpl
home: https://github.com/Senzing/charts/tree/main/charts/senzing-redoer
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
  - senzing
  - redo
  - kafka
  - rabbitmq
  - azure service bus
maintainers:
  - email: support@senzing.com
    name: Senzing
name: senzing-redoer
sources:
  - https://github.com/Senzing/charts/tree/main/charts/senzing-redoer
  - https://github.com/Senzing/redoer
type: application
version: 2.4.0
