affinity: {}

deployment:
  metadata:
    annotations:
  spec:
    template:
      metadata:
        annotations:

fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/redoer
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

senzing:
  azureConnectionString: ""
  azureFailureConnectionString: ""
  azureFailureQueueName: ""
  azureInfoConnectionString: ""
  azureInfoQueueName: ""
  azureQueueName: ""
  configPath: ""
  databaseUrl: ""
  debug: ""
  delayInSeconds: ""
  engineConfigurationJson: ""
  entrypointSleep: ""
  exitOnThreadTermination: ""
  expirationWarningInDays: ""
  kafkaBootstrapServer: ""
  kafkaFailureBootstrapServer: ""
  kafkaFailureTopic: ""
  kafkaInfoBootstrapServer: ""
  kafkaInfoTopic: ""
  kafkaRedoBootstrapServer: ""
  kafkaRedoGroup: ""
  kafkaRedoTopic: ""
  logLevel: ""
  logLicensePeriodInSeconds: ""
  monitoringPeriodInSeconds: ""
  mountOptIbm: false
  mountOptMicrosoft: false
  persistentVolumeClaim: ""
  queueMaxSize: ""
  rabbitmqDeliveryMode: ""
  rabbitmqExchange: ""
  rabbitmqFailureExchange: ""
  rabbitmqFailureHost: ""
  rabbitmqFailurePassword: ""
  rabbitmqFailureQueue: ""
  rabbitmqFailureRoutingKey: ""
  rabbitmqFailureUsername: ""
  rabbitmqFailureVirtualHost: ""
  rabbitmqHearbeatInSeconds: ""
  rabbitmqHost: ""
  rabbitmqInfoExchange: ""
  rabbitmqInfoHost: ""
  rabbitmqInfoPassword: ""
  rabbitmqInfoQueue: ""
  rabbitmqInfoRoutingKey: ""
  rabbitmqInfoUsername: ""
  rabbitmqInfoVirtualHost: ""
  rabbitmqPassword: ""
  rabbitmqPrefetchCount: ""
  rabbitmqReconnectDelayInSeconds: ""
  rabbitmqRedoExchange: ""
  rabbitmqRedoHost: ""
  rabbitmqRedoPassword: ""
  rabbitmqRedoQueue: ""
  rabbitmqRedoRoutingKey: ""
  rabbitmqRedoUsername: ""
  rabbitmqRedoVirtualHost: ""
  rabbitmqUseExistingEntities: ""
  rabbitmqUsername: ""
  rabbitmqVirtualHost: ""
  redoRetryLimit: ""
  redoRetrySleepTimeInSeconds: ""
  redoSleepTimeInSeconds: ""
  resourcePath: ""
  sleepTimeInSeconds: ""
  sqsFailureQueueUrl: ""
  sqsInfoQueueUrl: ""
  sqsRedoQueueUrl: ""
  subcommand: redo
  supportPath: ""
  threadsPerProcess: ""

service:
  port: 80
  type: ClusterIP

tolerations: []
