affinity: {}

deployment:
  metadata:
    annotations:
  spec:
    template:
      metadata:
        annotations:

fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/apt
  tag: latest

imagePullSecrets: []

mssql:
  acceptEula: ""

nameOverride: ""
nodeSelector: {}
rbacEnabled: false
replicaCount: 1
resources: {}

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

senzing:
  acceptEula: ""
  mountOptMicrosoft: false
  persistentVolumeClaim: senzing-persistent-volume-claim

tolerations: []
